[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/booking"
  to = "/booking.html"
  status = 200

[[redirects]]
  from = "/flights"
  to = "/flights.html"
  status = 200

[[redirects]]
  from = "/mybookings"
  to = "/mybookings.html"
  status = 200

[[redirects]]
  from = "/splitpay"
  to = "/splitpay.html"
  status = 200

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
